spring:
  application:
    name: java-table-tennis

  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    hikari:
      username: sa
      password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true